# https://www.netlify.com/docs/netlify-toml-reference/

# Builds initiated from any branch commit (except Master)
[context.branch-deploy]
  command = "npm run generate"    
  API_URL = 'https://us-central1-bnbcrate-dev.cloudfunctions.net/'

# Env variables for above
[context.branch-deploy.environment]
  BUILD_SOURCE = 'netlify'
  NODE_ENV = "development"